### ISSUE TITLE
Mobile Nav Menu Open/Close animation

### ISSUE THREAD

**Issue by ajayesivan** [zympl/leeway-website#82]
https://github.com/zympl/leeway-website/assets/19279756/da6329a2-e7b7-420a-aa1c-f492321e0397

Add mobile navigation menu open & close animation as shown in the above video.

Tip: This is a simple animation that can be achieved using the `transition` and `transform` CSS properties.

**Comment by Adhithyarajan** [comment]
I need help with this # 82

**Comment by ajayesivan** [comment]
@Adhithyarajan Could you elaborate on the specific challenges or areas where you're encountering difficulties?

**Comment by ajayesivan** [comment]
Did you learn about `transition` & `transform` css properties?

**Comment by Adhithyarajan** [comment]
Yes

**Comment by ajayesivan** [comment]
Just to make sure that you have a basic idea about how to handle animations in CSS please watch this: https://youtu.be/SgmNxE9lWcY.

The current implementation will need some tweaks in addition to just adding CSS properties. Here: https://github.com/zympl/leeway-website/blob/ef4cf89c6d69470240ceb9df5a6ae1f26e9f626d/public/app.js#L25 you can see that the current implementation use CSS display property to show & hide the menu. We need to change the implementation to use the `transform` property instead. Please let me know if you have further questions.

**Comment by Adhithyarajan** [comment]
I've added mobile navigation open menu animation and tried to do the same for close button by putting the code on various classes in CSS but didn't get the output.

**Comment by Adhithyarajan** [comment]
Can you please check the changes i've done till now so that you can figure out what is missing from my side or assign me a new issue.

**Comment by ajayesivan** [comment]
@Adhithyarajan Can you push the code & create a PR so I can check?
