### ISSUE TITLE
Create an empty shell for the how it works demo

### ISSUE THREAD

**Issue by ajayesivan** [zympl/leeway-website#94]
Design: https://www.figma.com/file/rd8upWhFjqFRaX4hKTTOh3/leeway?type=design&node-id=1252-1869&t=ONt0CmpmcSkCKRD1-4

- In the desktop view replace the image in how it works section with a rectangle `div` (check design for style).
- On mobile & tablet keep the existing image.

**Comment by Adhithyarajan** [comment]
I clicked close issue by mistake. Sorry ! Can you help me to solve this below screenshot. 
![SAVE_20230620_155537](https://github.com/zympl/leeway-website/assets/99787623/1318674f-42f9-4223-8cd8-5aa3234a1b54)
